<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-SLURSDT2" ignored="0" name="wangdonghui" tests="13" failures="3" timestamp="29 十二月 2018 11:19:43 GMT" time="308.262" errors="0">
  <testcase name="addcourse_coment" time="13.735" classname="test.AddComment_test">
    <failure type="java.lang.AssertionError" message="expected [您的评论已发表成功] but found [您的评论以发表成功！]">
      <![CDATA[java.lang.AssertionError: expected [您的评论已发表成功] but found [您的评论以发表成功！]
at test.AddComment_test.addcourse_coment(Unknown Source)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- addcourse_coment -->
  <testcase name="addcourse_reply" time="17.016" classname="test.AddReply_test"/>
  <testcase name="applyplace" time="18.398" classname="test.ApplyPlace_test"/>
  <testcase name="applyplace" time="18.458" classname="test.ApplyPlace_test"/>
  <testcase name="applyplace" time="18.447" classname="test.ApplyPlace_test"/>
  <testcase name="applyplace" time="18.494" classname="test.ApplyPlace_test"/>
  <testcase name="applyplace" time="9.843" classname="test.ApplyPlace_test">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at org.openqa.selenium.support.ui.Quotes.escape(Quotes.java:42)
at org.openqa.selenium.support.ui.Select.selectByValue(Select.java:197)
at com.webtest.core.WebDriverEngine.selectByValue(WebDriverEngine.java:226)
at test.ApplyPlace_test.applyplace(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- applyplace -->
  <testcase name="personalMessage" time="26.914" classname="test.ChangePersonalMessage_test"/>
  <testcase name="continueSC" time="17.073" classname="test.ContinueSC_test"/>
  <testcase name="createcourse" time="20.544" classname="test.CreateCourse_test"/>
  <testcase name="login" time="10.638" classname="test.Login_test"/>
  <testcase name="login" time="10.052" classname="test.Login_test"/>
  <testcase name="login" time="9.974" classname="test.Login_test">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at action.Login_action.login(Unknown Source)
at test.Login_test.login(Unknown Source)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- login -->
</testsuite> <!-- wangdonghui -->
